# Generated by Django 3.1.7 on 2024-04-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0002_retailer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
