# Generated by Django 5.0.4 on 2024-05-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0004_alter_retailer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
