# Generated by Django 5.0.4 on 2024-04-22 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_number', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('JEANS', 'Jeans'), ('TSHIRT', 'T-Shirt')], max_length=50)),
                ('current_stock', models.IntegerField(default=0)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('landing_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dealer_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('colors', models.ManyToManyField(to='stock.color')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stock.product')),
            ],
        ),
        migrations.CreateModel(
            name='SizeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sizes', models.ManyToManyField(to='stock.size')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='available_size_groups',
            field=models.ManyToManyField(to='stock.sizegroup'),
        ),
    ]
