# Generated by Django 5.0.4 on 2024-04-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='default', max_length=7),
            preserve_default=False,
        ),
    ]
