# Generated by Django 5.0.4 on 2024-04-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_color_hex_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
