# Generated by Django 5.0.4 on 2024-04-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_product_description_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='landing_cost',
        ),
    ]
