# Generated by Django 5.0.4 on 2024-05-05 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('status', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_id', models.IntegerField()),
                ('order_key', models.CharField(max_length=100)),
                ('billing_details', models.JSONField()),
                ('shipping_details', models.JSONField()),
                ('payment_method', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=100)),
                ('customer_ip_address', models.GenericIPAddressField()),
                ('customer_user_agent', models.CharField(max_length=200)),
                ('created_via', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('cart_hash', models.CharField(max_length=100)),
                ('order_number', models.IntegerField()),
                ('meta_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=20)),
                ('order_id', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=20)),
                ('captured', models.BooleanField()),
                ('description', models.CharField(max_length=100)),
                ('vpa', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('acquirer_data', models.JSONField(blank=True, null=True)),
                ('upi_details', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('product_id', models.IntegerField()),
                ('variation_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_data', models.JSONField(blank=True, null=True)),
                ('meta_data', models.JSONField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoiceAPI.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='invoiceAPI.payment'),
        ),
    ]
