# Generated by Django 5.0.4 on 2024-05-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceAPI', '0004_alter_lineitem_cgst_alter_lineitem_igst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
