# Generated by Django 5.0.4 on 2024-05-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceAPI', '0007_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_sent',
            field=models.BooleanField(default=False),
        ),
    ]
