# Generated by Django 5.0.4 on 2024-05-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceAPI', '0008_invoice_invoice_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
