# Generated by Django 5.0.4 on 2024-05-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0006_rename_file_document_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='files',
            new_name='file',
        ),
    ]
