# Generated by Django 5.0.4 on 2024-05-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0007_rename_files_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='full_nameme',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
