# Generated by Django 5.0.4 on 2024-05-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0008_dealer_full_nameme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='full_nameme',
            new_name='full_name',
        ),
    ]
