# Generated by Django 5.0.4 on 2024-05-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0010_alter_dealer_first_name_alter_dealer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
