# Generated by Django 5.0.4 on 2024-05-27 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0012_remove_dealer_otp_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='dealers.dealer')),
            ],
        ),
    ]
