# Generated by Django 5.0.4 on 2024-05-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0013_dealer_gstin_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='last_name',
        ),
    ]
