# Generated by Django 3.1.7 on 2024-04-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20240424_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
