# Generated by Django 5.0.4 on 2024-05-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_is_approved_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Paid', 'Paid'), ('Completed', 'Completed')], default='Not Paid', max_length=20),
        ),
    ]
