# Generated by Django 5.0.4 on 2024-05-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Not Paid', max_length=20),
        ),
    ]
