# Generated by Django 5.0.4 on 2024-05-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_billingaddress_full_name_shippingaddress_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='company',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='company',
        ),
    ]
