name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Server
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22 # Explicitly set the SSH port if it's not the default 
          script: |
            cd /home/b2b_user/b2b 
            git pull origin main
            ./deploy.sh  # Execute your deploy.sh script

