name: Deploy to Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Runner IP Address
        uses: haythem/public-ip@v1.4
        id: get-my-ip

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -x  # Enable verbose logging for debugging in deploy.sh
            cd /home/b2b_user/b2b
            git pull origin main
            ./deploy.sh  # Execute the deployment script
            sudo supervisorctl restart gunicorn

      - name: Check Deployment Status and Notify
        if: always()
        env:
          DEPLOY_STATUS: ${{ job.status }}
          DEPLOY_EXIT_CODE: ${{ steps.deploy.outcome }}
          RUNNER_IP: ${{ steps.get-my-ip.outputs.ipv4 }}
        run: |
          if [ "$DEPLOY_STATUS" == "success" ]; then
            MESSAGE="Deployment from ($RUNNER_IP) to DigitalOcean succeeded on $(date)."
          else
            MESSAGE="Deployment from ($RUNNER_IP) to DigitalOcean failed on $(date) with exit code $DEPLOY_EXIT_CODE. Check logs for details."

            # Detailed error logs from deploy.sh (if available)
            if [ -f /home/b2b_user/b2b/deploy_logfile.log ]; then
              echo "----- BEGIN deployment.sh LOG -----" >&2
              cat /home/b2b_user/b2b/deploy_logfile.log >&2
              echo "----- END deployment.sh LOG -----" >&2
            fi
          fi

          # Send Slack Notification
          curl -X POST -H "Content-Type: application/json" -d '{
            "text": "'"$MESSAGE"'"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
