name: Deploy to Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -x  # Enable verbose logging for debugging in deploy.sh

            cd /home/b2b_user/b2b
            git pull origin main

            ./deploy.sh  # Execute the deployment script

            # Check the exit code of the deployment script
            if [ $? -ne 0 ]; then
              echo "Deployment failed with exit code $?" >&2

              # Detailed error logs from deploy.sh
              echo "----- BEGIN deployment.sh LOG -----" >&2
              cat /home/b2b_user/b2b/deploy_logs.txt >&2  # Assuming your deploy.sh script logs to this file
              echo "----- END deployment.sh LOG -----" >&2

              # Slack Notification
              curl -X POST -H "Content-Type: application/json" -d '{
                "text": "Deployment to DigitalOcean failed on $(date) with exit code $?. Check logs for details."
              }' ${{ secrets.SLACK_WEBHOOK_URL }}
              
              exit 1  # Fail the workflow
            fi
